In [48]:
from dotenv import load_dotenv
import os
import psycopg2
import pandas as pd
import requests

In [2]:
# load_dotenv()

True

In [235]:
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
dbname = os.getenv("DB_NAME")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

In [236]:
def get_db_conn():
    try:
        conn =psycopg2.connect(
            host = os.getenv("DB_HOST"),
            port = os.getenv("DB_PORT"),
            dbname = os.getenv("DB_NAME"),
            user = os.getenv("DB_USER"),
            password = os.getenv("DB_PASSWORD")
        )
        print("Connected to db")
        return conn
        
    except psycopg2.OperationalError as error:
        print(f'Could not connect because: {error}')
        return None


conn = get_db_conn()

cursor = conn.cursor()
cursor.execute("SELECT * FROM users ")

columns = []
for desc in cursor.description: 
    columns.append(desc[0])

df = pd.DataFrame(cursor.fetchall(), columns=columns )

conn.close()

In [50]:
load_dotenv()
MOVIEDB_TOKEN = os.getenv("MOVIE_DB_TOKEN")

In [64]:

def get_movies_results(results):
    movies=[]
    
    for movie in results: 
        movie_data ={
            "id": movie['id'],
            "title": movie["title"],
            "original_language": movie["original_language"],
            "release_date": movie["release_date"],
            "popularity": movie["popularity"], 
            "vote_average": movie["vote_average"], 
            "vote_count": movie["vote_count"]
        }
        
        movies.append(movie_data)
    
    return movies
      

def get_movies_details(movie_id): 
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    response = requests.get(url,headers=headers)
    data = response.json() 
    movie_genres =[] 

    # Extraction genre du film
    for genre in data['genres']: 
        genre_data={
            'movie_id': movie_id,
            'genre': genre['name']
        }
        movie_genres.append(genre_data)
    
    movie_details ={
        'movie_id': movie_id, 
        'budget': data['budget'], 
        'revenue': data['revenue'], 
        'runtime': data['runtime']
    }

    return  movie_genres, movie_details

In [65]:
headers= {
    "accept": "application/json",
    "Authorization": f"Bearer {MOVIEDB_TOKEN}"
}

all_movies = []


for page_num in range(1,4): 
    url =f"https://api.themoviedb.org/3/movie/popular?page={page_num}" 
    response = requests.get(url,headers=headers)
    data = response.json() 
    results = data['results']

    movie_results = get_movies_results(results)
    all_movies.extend(movie_results)

df_movies = pd.DataFrame(all_movies) 


movies_genres=[]
movies_details = []

for movie_id in df_movies.id: 
    movie_genres,movie_details_data = get_movies_details(movie_id) 
    movies_genres.extend(movie_genres) 
    movies_details.append(movie_details_data) 


df_movie_genre = pd.DataFrame(movies_genres)  
df_movies_details = pd.DataFrame(movies_details) 
df_all_movies = df_movies.merge(df_movies_details, left_on = "id", right_on= "movie_id") 
df_all_movies = df_all_movies.drop("movie_id", axis=1)

In [74]:
df_all_movies = df_movies.merge(df_movies_details, left_on = "id", right_on= "movie_id")

In [76]:
df_all_movies = df_all_movies.drop("movie_id", axis=1)

In [78]:
df_movie_genre.head()

   movie_id            genre
0   1236153  Science Fiction
1   1236153           Action
2   1236153         Thriller
3   1272837           Horror
4   1272837         Thriller

In [88]:
df_all_movies.head()

,id,title,original_language,release_date,popularity,vote_average,vote_count,budget,revenue,runtime
0,1236153,Mercy,en,2026-01-20,649.4032,7.054,468,60000000,49463290,99
1,1272837,28 Years Later: The Bone Temple,en,2026-01-14,281.8152,7.200,597,63000000,58586229,109
2,1244975,The Orphans,fr,2025-08-20,239.1588,6.043,47,0,0,95
3,1301306,A Woman Scorned,en,2025-06-09,233.8935,6.000,9,0,0,84
4,1253000,Deathstalker,en,2025-10-10,194.1675,6.290,50,100000,0,103

In [63]:
movie_id = 1236153
movies_genres=[]
movies_details = []

def get_movies_details(movie_id): 
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    response = requests.get(url,headers=headers)
    data = response.json() 
    movie_genres =[] 

    # Extraction genre du film
    for genre in data['genres']: 
        genre_data={
            'movie_id': movie_id,
            'genre': genre['name']
        }
        movie_genres.append(genre_data)

    # Extraction de  movie details

    # print(data.keys()) 
    
    movie_details ={
        'movie_id': movie_id, 
        'budget': data['budget'], 
        'revenue': data['revenue'], 
        'runtime': data['runtime']
    }

    return  movie_genres, movie_details

movie_genres,movie_details = get_movies_details(movie_id) 
movies_genres.extend(movie_genres) 
movies_details.append(movie_details)

In [ ]:
movie_id = 1236153

movies_details = []
movies_genres = []

def get_movies_details(movie_id): 
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    response = requests.get(url,headers=headers)
    data = response.json() 

    # Fill here
    
    return movie_details, movie_genres


movie_details, movie_genres  = get_movies_details(movie_details)
movies_details.append(movie_details) 
movies_genres.extend(movie_genres)

In [31]:
movie_id = 1236153
url = f"https://api.themoviedb.org/3/movie/{movie_id}"
response = requests.get(url,headers=headers)
movie_details = response.json() 

movies_details = []
movies_genres = []

def get_movies_details(movie_id): 
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    response = requests.get(url,headers=headers)
    movie_details = response.json() 
    movie_genres =[]

    for genre in movie_details['genres']: 
        genre_data={
            'movie_id': movie_id,
            'genre': genre['name']}
        movie_genres.append(genre_data) 

    
    details_data ={
    'movie_id':movie_id, 
    'budget': movie_details['budget'] ,
    'revenue' : movie_details['revenue'], 
    'runtime':movie_details['runtime']}
    
        
    return details_data, movie_genres


    

movie_details, movie_genres  = get_movies_details(movie_id)

movies_details.append(movie_details) 
movies_genres.extend(movie_genres) 

movies_details_df = pd.DataFrame(movies_details) 
movies_genres_df = pd.DataFrame(movies_genres)

In [36]:

def get_movies_details(movie_id): 
    url = f"https://api.themoviedb.org/3/movie/{movie_id}"
    response = requests.get(url,headers=headers)
    movie_details = response.json() 
    movie_genres =[]

    for genre in movie_details['genres']: 
        genre_data={
            'movie_id': movie_id,
            'genre': genre['name']}
        movie_genres.append(genre_data) 

    
    details_data ={
    'movie_id':movie_id, 
    'budget': movie_details['budget'] ,
    'revenue' : movie_details['revenue'], 
    'runtime':movie_details['runtime']}
    
        
    return details_data, movie_genres

In [37]:
headers= {
    "accept": "application/json",
    "Authorization": f"Bearer {MOVIEDB_TOKEN}"
}

all_movies = []
movies_details = []
movies_genres = []



for page_num in range(1,4): 
    url =f"https://api.themoviedb.org/3/movie/popular?page={page_num}" 
    response = requests.get(url,headers=headers)
    data = response.json() 
    results = data['results']

    movie_results = get_movies_results(results)
    all_movies.extend(movie_results)

df_movies = pd.DataFrame(all_movies) 


for movie_id in df_movies.id: 
    movie_details, movie_genres  = get_movies_details(movie_id)
    movies_details.append(movie_details) 
    movies_genres.extend(movie_genres) 


movies_details_df = pd.DataFrame(movies_details) 
movies_genres_df = pd.DataFrame(movies_genres)

In [41]:
df_all_movies = df_movies.merge(movies_details_df, left_on='id', right_on='movie_id')

In [44]:
df_all_movies.head()

,id,title,original_language,release_date,popularity,vote_average,vote_count,movie_id,budget,revenue,runtime
0,1236153,Mercy,en,2026-01-20,649.4032,7.054,468,1236153,60000000,49463290,99
1,1272837,28 Years Later: The Bone Temple,en,2026-01-14,281.8152,7.200,597,1272837,63000000,58586229,109
2,1244975,The Orphans,fr,2025-08-20,239.1588,6.043,47,1244975,0,0,95
3,1301306,A Woman Scorned,en,2025-06-09,233.8935,6.000,9,1301306,0,0,84
4,1253000,Deathstalker,en,2025-10-10,194.1675,6.290,50,1253000,100000,0,103

In [47]:
movies_genres_df.head()

   movie_id            genre
0   1236153  Science Fiction
1   1236153           Action
2   1236153         Thriller
3   1272837           Horror
4   1272837         Thriller